version: '3'
services:
  gpio:
    container_name: home-sensors-gpio-connector
    build:
      context: gpio
    ports:
      - 5000:5000
    volumes:
      - /sys:/sys
      - ./gpio:/usr/src/app
    devices:
      - /dev/mem:/dev/mem
      - /dev/gpiomem:/dev/gpiomem

  php-fpm:
    container_name: home-sensors-backend
    build:
      context: php-fpm
    ports:
      - 9000
    volumes:
      - ./php:/var/www
      - /sys:/sys
    environment:
      - HOMESENSORS_DOMAIN=kevingemolo.ddns.net
      - HOMESENSORS_URL_ROOT=/sensori

  nginx:
    container_name: home-sensors-webserver
    image: nginx:alpine
    ports:
      - 4561:80
    volumes:
      - ./php:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
      - gpio
      - db

  db:
    container_name: home-sensors-db
    image: jsurf/rpi-mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sensori
      - MYSQL_DATABASE=HomeSensors
    volumes:
      - ./mysql/db:/var/lib/mysql

  checker:
    container_name: home-sensors-checker
    build:
      context: checker